# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30ae76303c51fa2a8cfdd1045bc74052d2acced7229199f6f8cab6b635ccd54a96fe8b266fdb31b90b3cbeb423bd279f0f029fa91556d628138bed29d9ceaba6

test:
  secret_key_base: f850b88c42803cd5e68557f6011feaf631161c011b5b4156d29f824d81035bb915968a0c5e73d8aea2ae8d647695f10384d2bdf7667b6352760cd98023fe183a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
